services:
  pv_hp_ctrl:
    build:
      context: .
    image: pv_hp_ctrl
    container_name: pvhpctrl
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    ports:
      - "8081:8081"
